### PR TITLE
Issue464 language filtering in input text

### LINKED ISSUE #464: Language filtering in input text
A model's attempts to process (in training/suggesting) text in a language different to the project's language are disadvantageous. Generally, any text-parts in a "foreign" language in a document probably just act as noise, but when the input-limit parameter (#446 and #452) is used, the drawback can be more serious: some thesis have abstracts in two or even three languages, and when the text is limited to a fixed number of characters, the retained text can mostly be in "foreign" languages. 

The foreign-language parts could be filtered out from the text that is passed to a backend (before input-limiting). 

One possible library to perform the actual language detection is [pycld3](https://pypi.org/project/pycld3/). It is much faster than [langdetect](https://pypi.org/project/langdetect/), does not require dependencies to be manually installed (installation is using Wheel for Python versions  3.5, 3.6, 3.7, and 3.8), and has Apache 2.0 license. The detected language is given as BCP-47-style language code which is used in Annif too.

The filtering could be optional with a common backend-parameter boolean switch.

### PR DESCRIPTION
**Pull request by juhoinkinen**
This is a draft PR with an initial implementation for the language-filtering feature, closes #464. 

~The branch of this PR is based on the input-transform branch (not yet in master), so PR #496 needs to be merged first to master.~ (Done.)

Needs finalizing and testing.

### CODE REVIEW

**Comment by juhoinkinen** [comment]
Rebased on master (as the PR #496 of input-transform functionality was merged to it) and force-pushed.

**Comment by juhoinkinen** [comment]
Rebased on master and force-pushed.

**Comment by juhoinkinen** [comment]
I added the `text_min_length` parameter, so language filtering of short texts can be bypassed. I think the user should remain responsible on the correctness of short texts, and this prevents somewhat embarrassing cases where a mistake in language detection would filter out all text input. (E.g. "Porovuosi : tutkija pororenkinä Sompiossa" is detected to be Lithuanian with prob. 0.84.). With this parameter set to 500 chars most of the Finna training documents are bypassing the language filtering, but that data set could and maybe should) be cleaned outside Annif.

 The `sentence_min_length` parameter is used to bypass language filtering of short sentences, for which the lang detection is unreliable.

**Comment by juhoinkinen** [comment]
Rebased & force-pushed to include the recent fix #528.

**Comment by juhoinkinen** [comment]
The [evaluation results](https://docs.google.com/spreadsheets/d/1kssU1w9xXbBcp_Wco_El4G827-OergyuWH5pF1vDciQ/edit#gid=810296471) for the current implementation most notably show improvement in the Bonsai model for JYU theses. I think this comes just from the initial motivation for the language filtering (in theses there are abstracts in "foreign" languages and when truncating the text input to 5000 chars the retained parts end up including a large "foreign" language text, which is unuseful for backends).

Bonsai model for Vapaakappaleet worsen by 1 %-point essentially zeroing the average improvement for Bonsai model. I tried to see why is this by checking what does the filtering remove, but in general the filtering works as expected and removes only non-Finnish sentences (and now when training with Finna data essentially nothing is removed). The only idea I have is that those non-Finnish parts include abbreviations, names etc. and removing those is disadvantageous .

The results for other backends on average show very slight improvement.

How does this look @osma?

**Review by osma — CHANGES_REQUESTED** [review]
Code looks good. The only issue I see is that pycld3 is native code (prebuilt wheels are available for macOS and Linux, but not Windows) and in alpha status. It would be better to make it an optional dependency.

**Pull request merged**
