### PR TITLE
Add spaCy analyzer

### LINKED ISSUE #374: spaCy analyzer
We could add an analyzer based on spaCy. It would enable support for some new languages and possibly also give better results for eg English and German than the current snowball analyzer.

Getting the full benefit of spaCy may require some internal API changes because it is more object oriented than NLTK and processes whole sentences instead of just individual words, taking some of the context into account.

This would be an optional feature as spaCy is implemented as a native code extension, not just pure Python.

### PR DESCRIPTION
**Pull request by osma**
Initial draft PR of new spaCy based (optional) analyzer.
Fixes #374

TODO items:

- [x] Option to force lowercasing of lemmas
- [ ] ~~Test with Swedish (which doesn't have a complete pretrained model) and adapt the code as necessary~~ Out of scope for now
- [x] Adapt YAKE backend so it doesn't do word-by-word normalization
- [x] Add English simple model to Docker image
- [x] Add wiki documentation: what the analyzer is, how to install, how to add more languages (native install & Docker case)

### CODE REVIEW

**Comment by osma** [comment]
It's working now (at least for the tfidf backend) but pretty slow - at least an order of magnitude slower than the Snowball analyzer. I think some batching must be used to make it more efficient, but that requires changes to the Analyzer API as well as to individual backends.

**Comment by osma** [comment]
Rebased and force-pushed.

There is a new release of spaCy (3.2.0) available, should test that.

**Comment by osma** [comment]
Rebased on current master, fixed conflicts and force-pushed.

**Comment by osma** [comment]
Ready for review!

Things I'm a bit unsure about:

- Does this actually work with all relevant backends? Especially YAKE, where I adjusted the way the backend calls the analyzer.
- Are the Dockerfile changes sensible? I.e. adding spacy as a default extension and downloading spacy models based on a build argument.

**Comment by osma** [comment]
Added wiki documentation:

- https://github.com/NatLibFi/Annif/wiki/Analyzers#spacy-analyzer
- https://github.com/NatLibFi/Annif/wiki/Optional-features-and-dependencies#spacy-analyzer
- https://github.com/NatLibFi/Annif/wiki/Usage-with-Docker#customizing-spacy-models

**Comment by juhoinkinen** [comment]
> Things I'm a bit unsure about:
> 
>     * Does this actually work with all relevant backends? Especially YAKE, where I adjusted the way the backend calls the analyzer.
> 
>     * Are the Dockerfile changes sensible? I.e. adding spacy as a default extension and downloading spacy models based on a build argument.

Works with YAKE, and Spacy analyzer also somewhat improved evaluation results compared to Snowball analyzer (on JYU test set F1@5 0.1706 -> 0.1870).

Dockerfile looks good to me. (The three tries for timeouts in downloading ntlk data was originally added for builds by/in Drone, as there were some network problems in Drone at that time, but I think the situation has improved now.)

Just one point to consider: if Spacy model has not been loaded, a bit lengthy traceback is shown ending `OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.` The ending is quite self-explanatory, so no big deal.

**Review by juhoinkinen — APPROVED** [review]

**Comment by osma** [comment]
I compared this to Snowball using the Annif-tutorial yso-nlf data sets and the three backend configurations (tfidf, mllm, omikuji-parabel) used in the tutorial. Results (best score for each backend type highlighted):

| backend | train set   | analyzer    | train jobs | train time | train RSS | eval set    | eval jobs | eval time | eval RSS | F1@5   | NDCG   |
| ------- | ----------- | ----------- | ---------- | ---------- | --------- | ----------- | --------- | --------- | -------- | ------ | ------ |
| tfidf   | yso-finna   | snowball    | 1          | 384.65     | 1528848   | jyu (n=300) | 4         | 166.86    | 590304   | **0.1812** | **0.2551** |
| tfidf   | yso-finna   | spacy       | 1          | 4,676.27   | 1614240   | jyu (n=300) | 4         | 1,171.48  | 3580224  | 0.1749 | 0.2476 |
| tfidf   | yso-finna   | spacy-lower | 1          | 4,692.22   | 1596052   | jyu (n=300) | 4         | 1,184.68  | 3570112  | 0.1749 | 0.2476 |
| mllm    | jyu (n=400) | snowball    | 4          | 771.82     | 2082856   | jyu (n=300) | 4         | 414.50    | 572140   | **0.2933** | **0.4043** |
| mllm    | jyu (n=400) | spacy       | 4          | 3,755.26   | 2124704   | jyu (n=300) | 4         | 2,321.21  | 677976   | 0.2871 | 0.3966 |
| mllm    | jyu (n=400) | spacy-lower | 4          | 3,724.93   | 2125776   | jyu (n=300) | 4         | 2,234.06  | 687532   | 0.2843 | 0.3868 |
| omikuji | yso-finna   | snowball    | 8          | 2,874.95   | 5285764   | jyu (n=300) | 4         | 166.33    | 1561728  | 0.3078 | 0.4253 |
| omikuji | yso-finna   | spacy       | 8          | 7,045.99   | 5513900   | jyu (n=300) | 4         | 1,169.09  | 4713760  | 0.3148 | 0.4312 |
| omikuji | yso-finna   | spacy-lower | 8          | 7,062.35   | 5830028   | jyu (n=300) | 4         | 1,129.53  | 4708832  | **0.3290** | **0.4451** |

Observations:

- spaCy is much much slower than Snowball (not entirely unexpected as it is a lot more sophisticated)
- train memory usage was a bit higher for spaCy (vs Snowball) but the differences were quite small
- eval memory usage of spaCy was much higher (compared to Snowball) for tfidf and omikuji, but not much higher for MLLM - not sure why but maybe it will become clear after some thinking
- the eval results for tfidf and mllm were worse than Snowball, but with Omikuji there was a small improvement (and the lowercased version was better than plain)

The point of these experiments was to check that the analyzer works reasonably well with those backends, not that the results are necessarily better in terms of F1 scores etc. spaCy has other advantages, especially the many languages it supports.

**Comment by osma** [comment]
I also tested svc and fasttext backends using the 20news data set in Annif-corpora. Results:

| backend  | train set    | analyzer    | train jobs | train time | train RSS | eval set    | eval time | eval RSS | P@1    | NDCG   |
| -------- | ------------ | ----------- | ---------- | ---------- | --------- | ----------- | --------- | -------- | ------ | ------ |
| svc      | 20news-train | snowball    | not set    | 30.14      | 557936    | 20news-test | 40.73     | 458092   | 0.6819 | 0.7999 |
| svc      | 20news-train | spacy       | not set    | 203.95     | 795692    | 20news-test | 156.83    | 706480   | 0.6840 | 0.8015 |
| svc      | 20news-train | spacy-lower | not set    | 203.23     | 789280    | 20news-test | 155.10    | 698340   | 0.6840 | 0.8015 |
| fasttext | 20news-train | snowball    | not set    | 91.96      | 631684    | 20news-test | 32.81     | 477348   | 0.4859 | 0.6924 |
| fasttext | 20news-train | spacy       | not set    | 259.54     | 769736    | 20news-test | 157.06    | 501760   | 0.4792 | 0.6862 |
| fasttext | 20news-train | spacy-lower | not set    | 251.19     | 775568    | 20news-test | 157.20    | 497220   | 0.4846 | 0.6891 |

Observations:

- spaCy was again much slower than Snowball
- memory usage wasn't dramatically higher
- results improved a bit for SVC, but were worse for fastText

I'd say this is good enough, I will check a few final things (including the error shown when a model doesn't exist, thanks @juhoinkinen!) and then merge this.

**Pull request merged**
