### PR TITLE
Issue250 support backend param option in train and learn commands

### PR DESCRIPTION
**Pull request by juhoinkinen**
This closes issue #250.

### CODE REVIEW

**Comment by juhoinkinen** [comment]
A few question on the way backend parameters are handled.

Here https://github.com/NatLibFi/Annif/blob/master/annif/backend/backend.py#L42 the `beparams` are  first taken from the object's attribute, then updated if there are `params` coming from CLI option, and finally passed in `_suggest` call. However,  for `limit` at least TFIDF and fastText backends use the original `params` attribute, not the passed `params` variable: 
https://github.com/NatLibFi/Annif/blob/master/annif/backend/tfidf.py#L54
https://github.com/NatLibFi/Annif/blob/master/annif/backend/fasttext.py#L116

However, the `chunksize` is taken from passed `params`:
https://github.com/NatLibFi/Annif/blob/master/annif/backend/mixins.py#L23

Is the intention that `limit` should not be overriden by `--backend-param`, or can that be changed to come from the passed `params`? 

Overall, is passing `params` variable necessary, as updating the object's `params` attribute would seem simpler? E.g. at line https://github.com/NatLibFi/Annif/blob/master/annif/backend/backend.py#L44

**Comment by osma** [comment]
You found some genuine inconsistencies there :)

A few thoughts about how parameter handling in backends should be done, and a comparison with the current (somewhat broken) situation.

* in backend classes, `self.params` should contain the parameters defined in `projects.cfg` (as is already the case) - perhaps this field could be renamed to something a bit more specific, e.g. `self.config_params`
* `suggest`, `train` and `learn` methods should take a `params` attribute (only `suggest` has it currently); this would be used to pass parameters set via CLI options
* the backends should not use `self.params` (or `self.config_params` if renamed) directly; instead, the passed `params` attribute should override parameters from the config file (as is done [here](https://github.com/NatLibFi/Annif/blob/master/annif/backend/backend.py#L42) - but perhaps there could be a helper method that does this)
* backend code should not assume that a particular parameter always exists; for example, `params['limit']` should be changed to `params.get('limit', self.DEFAULT_LIMIT)`; see #273 for some thoughts on this 

More generally, I think it would be helpful if backend classes explicitly defined the backend-specific (hyper)parameters they need. This information could be used e.g. for hyperparameter optimization (see #240). [fasttext](https://github.com/NatLibFi/Annif/blob/master/annif/backend/fasttext.py#L19), [vw_multi](https://github.com/NatLibFi/Annif/blob/master/annif/backend/vw_multi.py#L19) and [vw_ensemble](https://github.com/NatLibFi/Annif/blob/master/annif/backend/vw_ensemble.py#L26) already sort of do this in their own way, but the parameter definitions should be standardized and probably hyperopt would need more information about the parameters - for example the minimum and maximum values. This can be left for later, but it's probably useful to keep in mind when parameter handling code is modified.

**Comment by juhoinkinen** [comment]
Usage example (with debugging to show passed param values): 
```
$ annif train fasttext-fi tests/corpora/archaeology/documents_10_lines.tsv -b fasttext.dim=1 --backend-param fasttext.lr=42.1 --backend-param fasttext.epoch=0 -v DEBUG
debug: creating app with configuration annif.default_config.Config
debug: CLI option overriding parameter for backend fasttext: dim=1
debug: CLI option overriding parameter for backend fasttext: lr=42.1
debug: CLI option overriding parameter for backend fasttext: epoch=0
...
Backend fasttext: creating fastText model
debug: Backend fasttext: Model parameters: {'dim': 1, 'lr': 42.1, 'epoch': 0, 'loss': 'hs'}
Read 0M words
Number of words:  56
Number of labels: 15
Progress: 100.0% words/sec/thread:       0 lr:  0.000000 loss:  0.000000 ETA:   0h 0m
```

This PR introduces also the following:
- Simple validation of the passed backend-params, for example: 
```
$ annif train fasttext-fi tests/corpora/archaeology/documents_10_lines.tsv -b tfidf.dim=1 
Error: Error: The backend tfidf in CLI option "-b tfidf.dim=1" not matching the project backend fasttext.
```

- Raising `NotSupportedException` when trying to train ensemble backend:
```
$ annif train ensemble-fi ~/annif-projects/Annif-corpora/training/yso-finna-fi.tsv.gz 
Error: Error: Training ensemble model is not possible.
```

**Comment by osma** [comment]
Let's get back to this after PR #322 has been merged. Then the changes from `master` need to be merged into this branch.

**Comment by juhoinkinen** [comment]
> This pull request **introduces 1 alert** when merging [ba9edb8](https://github.com/NatLibFi/Annif/commit/ba9edb81034d45fea91a78484f37d24ab6547283) into [06f5221](https://github.com/NatLibFi/Annif/commit/06f52218b10e8bc43847a7ddd2ee4e9590add70d) - [view on LGTM.com](https://lgtm.com/projects/g/NatLibFi/Annif/rev/pr-093a8c9792de25d88b8b26afbb766fa34d7be749)
> 
> **new alerts:**
> 
>     * 1 for Non-iterable used in for loop

This alert seems like [the reported false positive](https://github.com/Semmle/ql/issues/2137) (the fix for that is merged to Semmle/ql master, but I could not find out which version of Semmle is run in lgtm.com).

**Pull request merged**
