### PR TITLE
Set Min Token Size to Two

### PR DESCRIPTION
**Pull request by mo-fu**
The changes in this PR will decrease the min token size for the analyzer to two. As discussed in #456 the impact on run time is not very large.

### CODE REVIEW

**Comment by juhoinkinen** [comment]
I checked the effect of this PR (changing min token size from 3 to 2), training on Finna data set, evaluating on JYX thesis test set. 

Omikuji Parabel - Finnish:
| Stat | Value for 2 | Value for 3 |
|-|-|-|
| F1@5 | 0.3251 | 0.3386 
| NDCG | 0.4393 | 0.4560 
| NDCG@5 | 0.4250 | 0.4407 
| train time (min) | 174 | 192
| omikuji-train.txt (MB) | 955 | 1012

Omikuji Parabel - English:
| Stat | Value for 2 | Value for 3 |
|-|-|-|
| F1@5 | 0.3157 |  0.3115
| NDCG | 0.4345 |  0.4292
| NDCG@5 | 0.4380 |  0.4319
| train time (min) | 36 | 33
| omikuji-train.txt (MB) | 373 | 422

TFIDF - Finnish (training only on the first dataset file):
| Stat | Value for 2 | Value for 3 |
|-|-|-|
| F1@5 | 0.2277 |  0.2745
| NDCG | 0.3165 | 0.3833 
| NDCG@5 | 0.3169 | 0.3752 
| train time (min) |  11 | 7

The sizes of model files do not really change. I run these on my laptop, so timings are not very accurate. Analyzer was Snowball for all.

So for English slight increase in quality, but unfortunately for Finnish Parabel model I get ~1 %-point decrease and more for TFIDF. I should probably have used Voikko instead of Snowball for Finnish, I'll check if that makes a difference.

**Comment by osma** [comment]
Thanks for the additional testing @juhoinkinen!

I think that getting an improvement for English but worse results for Finnish should be an argument for making this setting configurable instead of using a fixed value of either 2 or 3. I suggested making this value configurable in [this comment](https://github.com/NatLibFi/Annif/issues/456#issuecomment-779039463), perhaps it would be worth revisiting that idea?

**Comment by juhoinkinen** [comment]
Using Voikko instead of Snowball (training on only one file, `yso-finna-fi-01.tsv.gz`):

Omikuji Parabel - Finnish:
| Stat | Value for 2 | Value for 3 |
|-|-|-|
| F1@5 | 0.2950 | 0.2972
| NDCG | 0.3949 |  0.4025
| NDCG@5 | 0.3852 | 0.3929
| train time (min) | 42 | 40
| omikuji-train.txt (MB) | 300 | 283

TFIDF - Finnish:
| Stat | Value for 2 | Value for 3 |
|-|-|-|
| F1@5 | 0.2316 | 0.2828
| NDCG | 0.3255 | 0.3923
| NDCG@5 | 0.3261 | 0.3881
| train time (min) | 8 | 13

**Comment by juhoinkinen** [comment]
I tested this with Voikko & Snowball, no problems :+1: 

Wiki needs to updated for this, at least [the Analyzers page](https://github.com/NatLibFi/Annif/wiki/Analyzers).

**Review by juhoinkinen — APPROVED** [review]

**Comment by juhoinkinen** [comment]
Thanks @mo-fu for the complexity fixes, seems ready, so I'll merge this.

**Pull request merged**
